#!/usr/bin/env python3
"""
tools/board.py - Platt Park live board build tool

  split   one-time: carve platt-park-live-board-v4.html into src/
            src/board.html            the markup, with @@css:..@@ / @@js:..@@ markers
            src/css/N-name.css        each <style> block, in page order
            src/js/N-name.js          each <script> block, in page order
            src/img/*.png             the embedded images, as files
  build   assemble src/ -> dist/platt-park-live-board-v4.html + dist/img/
            a build stamp goes in after <!DOCTYPE html> so the wall's ETag changes
            and the TV reloads itself within 5 minutes of a green build

After the split, EDIT src/ ONLY. The root html is generated by the Board workflow.
"""
import re, sys, os, base64, shutil, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
LIVE = ROOT / "platt-park-live-board-v4.html"
SRC  = ROOT / "src"
DIST = ROOT / "dist"

CSS_NAMES = ["fonts", "main", "scenepicker", "fit"]      # <style> blocks, page order
JS_NAMES  = ["app", "gear", "fit", "qol"]                # <script> blocks, page order
IMG_NAMES = ["logo", "ranger", "qr"]                     # <img src="data:..."> in page order

BLOCK = {"css": "style", "js": "script"}


def split():
    s = LIVE.read_text(encoding="utf-8")
    for d in ("css", "js", "img"):
        (SRC / d).mkdir(parents=True, exist_ok=True)

    for kind, names in (("css", CSS_NAMES), ("js", JS_NAMES)):
        tag = BLOCK[kind]
        n = [0]
        def repl(m, kind=kind, tag=tag, names=names):
            i = n[0]; n[0] += 1
            name = "%d-%s" % (i, names[i] if i < len(names) else kind + str(i))
            (SRC / kind / (name + "." + kind)).write_text(m.group(2), encoding="utf-8")
            return "<%s%s>@@%s:%s@@</%s>" % (tag, m.group(1), kind, name, tag)
        s = re.sub(r"<%s\b([^>]*)>([\s\S]*?)</%s>" % (tag, tag), repl, s)
        print("  %s: %d blocks" % (kind, n[0]))

    n = [0]
    def img(m):
        i = n[0]; n[0] += 1
        name = IMG_NAMES[i] if i < len(IMG_NAMES) else "img%d" % i
        (SRC / "img" / (name + ".png")).write_bytes(base64.b64decode(m.group(1)))
        return 'src="img/%s.png"' % name
    s = re.sub(r'src="data:image/png;base64,([A-Za-z0-9+/=]+)"', img, s)
    print("  img: %d files" % n[0])
    assert "data:image/png" not in s, "an image was not extracted"

    (SRC / "board.html").write_text(s, encoding="utf-8")
    print("  wrote src/board.html (%d KB)" % (len(s) // 1024))


def build():
    html = (SRC / "board.html").read_text(encoding="utf-8")
    missing = []
    def repl(m):
        p = SRC / m.group(1) / (m.group(2) + "." + m.group(1))
        if not p.exists():
            missing.append(str(p)); return ""
        return p.read_text(encoding="utf-8")
    html = re.sub(r"@@(css|js):([^@]+)@@", repl, html)
    if missing:
        sys.exit("missing parts: " + ", ".join(missing))
    assert "@@" not in html[:200] and "@@css" not in html and "@@js" not in html, "unresolved marker"

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    sha = os.environ.get("GITHUB_SHA", "local")[:7]
    head = "<!DOCTYPE html>"
    assert html.startswith(head), "board.html must start with <!DOCTYPE html>"
    html = head + "<!-- built %s from src @ %s - GENERATED FILE: edit src/, never this -->" % (stamp, sha) + html[len(head):]

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()
    (DIST / "platt-park-live-board-v4.html").write_text(html, encoding="utf-8")
    shutil.copytree(SRC / "img", DIST / "img")
    print("  built dist/platt-park-live-board-v4.html (%d KB) + %d images"
          % (len(html) // 1024, len(list((DIST / "img").iterdir()))))


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "split":
        if (SRC / "board.html").exists() and "--force" not in sys.argv:
            sys.exit("src/board.html already exists - the split is done; edit src/ and build")
        split()
    elif cmd == "build":
        build()
    else:
        sys.exit(__doc__)
